### ISSUE TITLE
Do you plan to migrate to a newer version core2.1?

### ISSUE THREAD

**Issue by sergeos** [jamesej/lyniconanc#4]
Is it planned to move?

**Comment by jamesej** [comment]
Thanks for asking the question. Lynicon is already compatible with Core 2.1, the setup docs are [here](https://lynicon.atlassian.net/wiki/spaces/LAC/pages/363495425/Installing+to+a+New+Project+-+VS2017+.Net+4.6.1+.Net+Standard+2.0+Core+2.1): It may be confusing because the test project in this repository is still built on Core 2.0. We may update that in 4 to 6 months as Core 2.1 becomes more mainstream. However it should be simple enough to do, essentially for the test project only follow Core 2.0 to Core 2.1 upgrade instructions such as can be found [here](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1).
